name: Build and Test

on: workflow_dispatch

#   push:
#     branches:
#       - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    inputs:
      pytestFlags:
        description: 'PyTest Flags'
        required: false
        default: ''
        type: string

    steps:
    - name: Install PyTest
      run: pip install pytest

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: make all

    - name: Wait for 10 seconds
      run: sleep 10

    - name: Run Tests
      run: make test ${{ inputs.pytestFlags }}
